//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHH_GRAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDATHANG
    {
        public string SOHOADON { get; set; }
        public string MAHANG { get; set; }
        public decimal GIABAN { get; set; }
        public decimal SOLUONG { get; set; }
        public Nullable<decimal> MUCGIAMGIA { get; set; }
    
        public virtual MATHANG MATHANG { get; set; }
        public virtual DONDATHANG DONDATHANG { get; set; }
    }
}
